### ISSUE TITLE
Drivers' Licence Endorsements

### ISSUE THREAD

**Issue by andytudhope** [Bit-Nation/bitnation-id#1]
Feature request from a citizen: Could you enhance the Bitnation ID to include endorsements for car/truck/motorcycle? I'm thinking that a person already has that and so it would be really simple to add an endorsement with a short blurb about the issuing agency, country, state, etc. Once that is possible, it will be possible to issue International Driving Permits.

**Comment by ETeissonniere** [comment]
That issue is nearly one year old, I am going to close it. Feel free to reopen if you think we missed something.
